Happy and sad paths for sign_up feature
CraftAcademy/rails_messaging_aug18 pull request #8
Opened 2018-09-19 14:43 UTC by danmalmx

##PT Link
https://www.pivotaltracker.com/story/show/160582768

## Sign_up feature created

* Test (feature) for happy and sad path:
    * Name, email, password and password confirmed
    * Name taken, password blank, password not matching 

What I've learned - how to test for both the happy and sad feature path.

2018-09-19 18:37 UTC, danmalmx commented
Completed

2018-09-20 11:30 UTC, faraznaeem requested changes

2018-09-20 11:30 UTC, faraznaeem commented on features/sign_up.feature
> +        Then I fill in "Name" with "Daniel"
`And`

2018-09-20 11:30 UTC, faraznaeem commented on features/sign_up.feature
> +        Then I fill in "Name" with "Daniel"
`And`

2018-09-20 11:30 UTC, faraznaeem commented on features/sign_up.feature
> +        Then I should see a message that states "Password can't be blank"
`And` in the other scenarios too.

2018-09-20 12:24 UTC, faraznaeem approved these changes

2018-09-20 12:24 UTC, merged